config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
root  "blogs#index"
devise_for :users
resources :users, only: [:show]
resources :conversations do
resources :messages
end
resources :favorites
  resources :blogs do
    resources :comments

    collection do
      post :confirm
    end
  end
  #resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    member do
      get :likes
    end

  end
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end
  def index
  @users =User.all
  @messages = @conversation.messages

  if @messages.length > 10
    @over_ten = true
    @messages = Message.where(id: @messages[-10..-1].pluck(:id))
  end

  if params[:m]
    @over_ten = false
    @messages = @conversation.messages
  end

  if @messages.last
    @messages.where.not(user_id: current_user.id).update_all(read: true)
  end

  @messages = @messages.order(:created_at)
  @message = @conversation.messages.build
end
def create
   @message = @conversation.messages.build(message_params)
   if @message.save
     redirect_to conversation_messages_path(@conversation, anchor: 'latest_position')
   else
     render 'index'
   end
 end
 private

def message_params
  params.require(:message).permit(:body, :user_id)
end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<body class="bckg-im">
  <header class="123">
    <div class="en_tete">
      <%= image_tag "header_border.png", class: 'header_border' %>
      <%= link_to blogs_path do %>
        <%= image_tag "insta.png", class: 'insta_logo' %>
      <% end %>

      <span class='recherche'></span>
      <%= link_to blogs_path do %>
      <%= image_tag "home.jpg", class: 'insta_icon' %>
      <%end%>
      <%= link_to likes_user_path(current_user.id) do %>
      <%= image_tag "heart_img.png", class: 'insta_icon' %>
      <% end %>
      <%= link_to user_path(current_user.id) do %>
      <%= image_tag "user.png", class: 'insta_icon' %>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete,data: { confirm: 'Etes Vous Sur ?' } do %>
      <%= image_tag "logout.png", class: 'insta_icon' %>
      <% end %>
      <% if current_user.admin? %>
     <%= link_to rails_admin_path do %>
     <%= image_tag "admin.png", class: 'insta_icon' %>
     <% end %>
     <% end %>
    </div>
  </header>
<main>
<% if @over_ten %>
  <%= link_to 'Previous message', '?m=all' %>
<% end %>
<div class="right_box">
<h2 class="comment">Users</h2>
<% @users.each do |user| %>
  <% if user.id != current_user.id %>
    <li>
      <div class="item">
        <%= link_to user.name, user %>
        <%= link_to 'Message', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
      </div>
    </li>
  <% end %>
<% end %>
</div>
<div class="left_box">
  <div class="share_box">
<div class="ui segment">
  <table>
        <tr>
          <td>
            <div class="main_box_head">
  <% @messages.each do |message| %>
    <% if message.body.present? %>
      <div class="item">
        <div class="content">
          <div class="comment"><strong class="info1"><%= message.user.name %></strong> <%= message.message_time %></div>
          <div class="list">
            <div class="item">
              <i class="right triangle icon"></i>
              <div class="comment">
              <%= message.body %> /
              <% if message.user == current_user %>
                <%= message.read ? 'Already read' : 'Unread' %>
                    <% end %>
                  </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <table>
        <td>
        <tr>
        <%= form_with(model: [@conversation, @message]) do |f| %>
          <div class="field">
            <table>
                  <tr>
                    <td>
            <%= f.text_area :body, class: "form-control" %>
          </div>
            <%= f.text_field :user_id, value: current_user.id, type: "hidden"  %>
          <div>
            <%= f.submit "send a message" %>
      </div>
    </td>
    </tr>
    </table>
   </div>
  </div>
<% end %>