config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
root  "blogs#index"
devise_for :users
resources :users, only: [:show]
resources :conversations do
resources :messages
end
resources :favorites
  resources :blogs do
    resources :comments

    collection do
      post :confirm
    end
  end
  #resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    member do
      get :likes
    end

  end
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
 validates :content, presence: true, unless: :image?
 mount_uploader :image, ImageUploader
 has_many :comments, dependent: :destroy
 has_many :favorites, dependent: :destroy
 has_many :users, through: :favorites

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
before_action :authenticate_user!
before_action :set_blog, only: [:show, :update, :destroy]

 def index
   @blogs = Blog.all.order(id: "desc")
   @useronline=[]
   @users = User.all
   @users.each do |user|
     if user.online? && user.id !=current_user.id
       @useronline << user.id
    end
    end
   @recipient=@useronline.sample
   puts "#{@recipient}"
 end

 def new
   @blog = Blog.new
 end

 def create
   @blog = current_user.blogs.build(blog_params)
   if params[:back]
     render :new
   else
     if @blog.save
       #ConfirmMailer.confirm_mail(@blog, current_user).deliver
       redirect_to blogs_path
     else
       render 'new'
     end
   end
 end

 def edit
   if Blog.find(params[:id]).user.name == current_user.name
     @blog = Blog.find(params[:id])
   else
     redirect_to blogs_path
   end
 end

 def update
   if @blog.update(blog_params)
     redirect_to blogs_path
   else
     render :edit
   end
 end

 def destroy
   @blog.destroy
   redirect_to blogs_path
 end

 def confirm
   @blog = current_user.blogs.build(blog_params)
   render :new if @blog.invalid?
 end

 def show
   @favoritess = current_user.favorites.find_by(blog_id: @blog.id)
   @comments = @blog.comments
   @comment = @blog.comments.build
 end

 private

 def blog_params
   params.require(:blog).permit(:title, :content, :image, :image_cache)
 end

 def set_blog
   @blog = Blog.find(params[:id])
 end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
   if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
     confirm_blogs_path
   elsif action_name == 'edit'
     blog_path
   end
 end
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2>You Have Made<%= @blog.errors.count %> Error(s)</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="comment">
    <%= form.label :image, "Image" %>
    <br>
    <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <br>
  <div class="comment">
    <%= form.label :content, "Comment" %>
    <br>
    <%= form.text_field :content, size: :"100*50", placeholder:"Hello World !!" %>
  </div>
  <br>
  <%= form.submit "Submit"%>
<% end %>
<br>
<%= link_to "Back", blogs_path %>

app/views/blogs/confirm.html.erb
<body class="bckg-im">
  <header class="123">
    <div class="en_tete">
      <%= image_tag "header_border.png", class: 'header_border' %>
      <%= link_to blogs_path do %>
        <%= image_tag "insta.png", class: 'insta_logo' %>
      <% end %>

      <span class='recherche'></span>
      <%= link_to blogs_path do %>
      <%= image_tag "home.jpg", class: 'insta_icon' %>
      <%end%>
      <% if @recipient.present? %>
       <%= link_to conversations_path(sender_id: current_user.id, recipient_id: @recipient), method: :post do %>
      <%= image_tag "insta_messenger.jpg", class: 'insta_icon' %>
      <% end %>
      <% end %>
      <%= link_to likes_user_path(current_user.id) do %>
      <%= image_tag "heart_img.png", class: 'insta_icon' %>
      <% end %>
      <%= link_to user_path(current_user.id) do %>
      <%= image_tag "user.png", class: 'insta_icon' %>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete,data: { confirm: 'Etes Vous Sur ?' } do %>
      <%= image_tag "logout.png", class: 'insta_icon' %>
      <% end %>
      <% if current_user.admin? %>
     <%= link_to rails_admin_path do %>
     <%= image_tag "admin.png", class: 'insta_icon' %>
     <% end %>
     <% end %>
    </div>
  </header>

<main>
<h3 class= "comment">Confirm ?</h3>
<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p class="comment"><%= @blog.content %></p>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
  <%= form.hidden_field :image_cache %>
  <br>
  <br>
  <%= form.submit "Submit" %>
  <br>
  <br>
  <%= form.submit "Back", name: 'Back'%>
<% end %>
</main>
</body>

app/views/blogs/edit.html.erb
<body class="bckg-im">
  <header class="123">
    <div class="en_tete">
      <%= image_tag "header_border.png", class: 'header_border' %>
      <%= link_to blogs_path do %>
        <%= image_tag "insta.png", class: 'insta_logo' %>
      <% end %>

      <span class='recherche'></span>
      <%= link_to blogs_path do %>
      <%= image_tag "home.jpg", class: 'insta_icon' %>
      <%end%>
      <% if @recipient.present? %>
       <%= link_to conversations_path(sender_id: current_user.id, recipient_id: @recipient), method: :post do %>
      <%= image_tag "insta_messenger.jpg", class: 'insta_icon' %>
      <% end %>
      <% end %>
      <%= link_to likes_user_path(current_user.id) do %>
      <%= image_tag "heart_img.png", class: 'insta_icon' %>
      <% end %>
      <%= link_to user_path(current_user.id) do %>
      <%= image_tag "user.png", class: 'insta_icon' %>
      <% end %>
        <%= link_to destroy_user_session_path, method: :delete,data: { confirm: 'Are You Sure ?' } do %>
      <%= image_tag "logout.png", class: 'insta_icon' %>
      <% end %>
      <% if current_user.admin? %>
     <%= link_to rails_admin_path do %>
     <%= image_tag "admin.png", class: 'insta_icon' %>
     <% end %>
     <% end %>
    </div>
  </header>

<main>
  <%= render 'form' %>
</main>
</body>

app/views/blogs/index.html.erb
<body class="bckg-im">
<header class="123">
  <div class="en_tete">
    <%= image_tag "header_border.png", class: 'header_border' %>
    <%= link_to blogs_path do %>
      <%= image_tag "insta.png", class: 'insta_logo' %>
    <% end %>

    <span class='recherche'></span>
    <%= link_to blogs_path do %>
    <%= image_tag "home.jpg", class: 'insta_icon' %>
    <%end%>
    <% if @recipient.present? %>
     <%= link_to conversations_path(sender_id: current_user.id, recipient_id: @recipient), method: :post do %>
    <%= image_tag "insta_messenger.jpg", class: 'insta_icon2' %>
    <% end %>
    <% end %>
    <%= link_to likes_user_path(current_user.id) do %>
    <%= image_tag "heart_img.png", class: 'insta_icon' %>
    <% end %>
    <%= link_to user_path(current_user.id) do %>
    <%= image_tag "user.png", class: 'insta_icon' %>
    <% end %>
    <%= link_to destroy_user_session_path, method: :delete,data: { confirm: 'Are You Sure ?' } do %>
    <%= image_tag "logout.png", class: 'insta_icon', id:'log' %>
    <% end %>
    <% if current_user.admin? %>
   <%= link_to rails_admin_path do %>
   <%= image_tag "admin.png", class: 'insta_icon' %>
   <% end %>
   <% end %>
  </div>
</header>

<main>

  <div class="left_box">
    <div class="share_box">
      <%= link_to new_blog_path do %>
      <%= image_tag "post.png", class: 'insta_icon' %>
      <% end %>
    </div>
    <% @blogs.each do |blog| %>
    <div class="main_box">
      <table>
        <tr>
          <td>
            <div class="main_box_head">
              <% if blog.user.image.file.nil? %>
                <%= image_tag 'no_profile_pic.png', class: 'contributer_img' %>
                <% else %>
                <%= image_tag blog.user.image.url, class: 'contributer_img' %>
              <% end %>
              <%= link_to "#{blog.user.name}", user_path(blog.user.id), class: 'contributer' %>
              <div class="main_box_menu">
                <%= link_to blog_path(blog.id) do %>
                <%= image_tag "details.png", class: 'insta_icon1', id:'details' %>
                <% end %>
                <% if current_user.id == blog.user.id %>
                <%= link_to edit_blog_path(blog.id) do %>
                <%= image_tag "edit.png", class: 'insta_icon1', id:'edit' %>
                <% end %>
                <%= link_to blog_path(blog.id), method: :delete ,data: { confirm: 'Are You Sure ?' } do %>
                <%= image_tag "delete.png", class: 'insta_icon1', id:'delete' %>
                <% end %>
              </div>
            </div>
          </td>
          <% end %>
        </tr>
        <tr>
          <td>
          <% if blog.image.file.nil? %>
            <% else %>
            <%= image_tag blog.image.url, class: 'main_box_img' %>
          <% end %>
          </td>
        </tr>
        <tr>
          <td>
          <div class="main_box_bottom">
            <% @favorite = current_user.favorites.find_by(blog_id: blog.id) %>
           <% if @favorite.present? %>
             <%= link_to favorite_path(id: @favorite.id), method: :delete do %>
               <%= image_tag "save_on_img.png", class: 'save_img' %>
             <% end %>
             <% else %>
             <%= link_to favorites_path(blog_id: blog.id), method: :post do%>
               <%= image_tag "save_off_img.png", class: 'save_img' %>
             <% end %>
           <% end %>

            <p class="comment1">
              <%= link_to "#{blog.user.name}", user_path(blog.user.id), class: 'contributer' %>
              <span>: <%= blog.content %></span>
            </p>
            <p class="upload_date"><%= blog.user.created_at.try(:strftime,"%D") %></p>
          </div>
          </td>
        </tr>
      </table>
    </div>
    <br>
    <br>
    <% end %>
    <br>
    <br>
  </div>

  <div class="right_box">
    <div class="login_user_profile">
      <% if current_user.image.file.nil? %>
        <%= image_tag 'no_profile_pic.png', class: 'login_user_img' %>
      <% else %>
        <%= image_tag current_user.image.url, class: 'login_user_img' %>
      <% end %>
      <div class="login_user_name">
        <p class="contributer">
          <%= link_to "#{current_user.name}", user_path(current_user.id), class: 'contributer' %>
        </p>
        <p>
        <%= link_to "#{current_user.name}", user_path(current_user.id), class: 'login_user_name' %>
        </p>
        <br>
        <br>
        <fieldset>
        <label class="info">[Welcome To NeedToTalk !!] <br> The place where people can share their problems and true feelings in a completely anonymous manner, place of emotional acceptance and healing !!</label>
     <footer class="comment">
          <p>~LS~</p>
          <p>NeedToTalk, From Negativity Emerge Positivity ! </p>
          <br>
          <p>© 2022 NeedToTalk</p>
          <br>
          <br>
    </footer>
  </div>
</main>
</body>

app/views/blogs/new.html.erb
<body class="bckg-im">
  <header class="123">
    <div class="en_tete">
      <%= image_tag "header_border.png", class: 'header_border' %>
      <%= link_to blogs_path do %>
        <%= image_tag "insta.png", class: 'insta_logo' %>
      <% end %>

      <span class='recherche'></span>
      <%= link_to blogs_path do %>
      <%= image_tag "home.jpg", class: 'insta_icon' %>
      <%end%>
      <% if @recipient.present? %>
       <%= link_to conversations_path(sender_id: current_user.id, recipient_id: @recipient), method: :post do %>
      <%= image_tag "insta_messenger.jpg", class: 'insta_icon' %>
      <% end %>
      <% end %>
      <%= link_to likes_user_path(current_user.id) do %>
      <%= image_tag "heart_img.png", class: 'insta_icon' %>
      <% end %>
      <%= link_to user_path(current_user.id) do %>
      <%= image_tag "user.png", class: 'insta_icon' %>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete,data: { confirm: 'Are You Sure ?' } do %>
      <%= image_tag "logout.png", class: 'insta_icon' %>
      <% end %>
      <% if current_user.admin? %>
     <%= link_to rails_admin_path do %>
     <%= image_tag "admin.png", class: 'insta_icon' %>
     <% end %>
     <% end %>
    </div>
  </header>


<main>
<%= render 'form' %>
</main>
</body>

app/views/blogs/show.html.erb
<body class="bckg-im">
  <header class="123">
    <div class="en_tete">
      <%= image_tag "header_border.png", class: 'header_border' %>
      <%= link_to blogs_path do %>
        <%= image_tag "insta.png", class: 'insta_logo' %>
      <% end %>

      <span class='recherche'></span>
      <%= link_to blogs_path do %>
      <%= image_tag "home.jpg", class: 'insta_icon' %>
      <%end%>
      <% if @recipient.present? %>
       <%= link_to conversations_path(sender_id: current_user.id, recipient_id: @recipient), method: :post do %>
      <%= image_tag "insta_messenger.jpg", class: 'insta_icon' %>
      <% end %>
      <% end %>
      <%= link_to likes_user_path(current_user.id) do %>
      <%= image_tag "heart_img.png", class: 'insta_icon' %>
      <% end %>
      <%= link_to user_path(current_user.id) do %>
      <%= image_tag "user.png", class: 'insta_icon' %>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete,data: { confirm: 'Are You Sure ?' } do %>
      <%= image_tag "logout.png", class: 'insta_icon' %>
      <% end %>
      <% if current_user.admin? %>
     <%= link_to rails_admin_path do %>
     <%= image_tag "admin.png", class: 'insta_icon' %>
     <% end %>
     <% end %>
    </div>
  </header>
<main>
  <% if current_user.id == @blog.user.id  %>
  <%= link_to 'Edit', edit_blog_path(@blog) %> |
  <%end%>
  <p>
    <% if @blog.image.file.nil? %>
      <% else %>
      <%= image_tag(@blog.image_url(:thumbnail), :alt => @blog.content) %>
      <% end %>
  </p>
  <div class="container">
  <p id="notice"><%= notice %></p>

  <div class="blog-text">
    <p class="comment"><strong class="comment">Contents</strong>：<%= @blog.content %></p>
  </div>
  <!-- Get the HTML id of this comments_area and update only that part of the div-->
  <div>
    <div id="comments_area">
      <!-- Render to display a list of posted comments on the blog details page -->
      <%= render partial: 'comments/index', locals: { comments: @comments,blog: @blog }%>
  </div>
  </div>

  <!-- Render to display the comment input field on the detail page of the blog -->
  <%= render partial: 'comments/form', locals: { comment: @comment, blog: @blog } %>


</div>
  <p class="upload_date"><%= @blog.user.created_at.try(:strftime,"%D") %></p>

  <br>
  <br>
  <%= link_to "Blog Screen", blogs_path %>
</main>
</body>