config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
root  "blogs#index"
devise_for :users
resources :users, only: [:show]
resources :conversations do
resources :messages
end
resources :favorites
  resources :blogs do
    resources :comments

    collection do
      post :confirm
    end
  end
  #resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    member do
      get :likes
    end

  end
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_blog, only: [:create, :edit, :update]
  def create
    @comment = @blog.comments.build(comment_params)
    @blog = Blog.find(params[:blog_id])
      @comment.user_id =current_user.id
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { redirect_to blog_path(@blog), notice: "Could'nt post..." }
      end
    end
  end
  def edit
    @comment = @blog.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'Editing comment'
      format.js { render :edit }
    end
  end
  def update
    @comment = @blog.comments.find(params[:id])
      respond_to do |format|
        if @comment.update(comment_params)
          flash.now[:notice] = 'Comment edited'
          format.js { render :index }
        else
          flash.now[:notice] = 'Failed to edit comment'
          format.js { render :edit }
        end
      end
  end
  # add to
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      flash.now[:notice] = 'Comment deleted'
      format.js { render :index }
    end
  end
  # So far
  private
  def comment_params
    params.require(:comment).permit(:content)
  end
  def set_blog
    @blog = Blog.find(params[:blog_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit.html.erb
<%= form_with(model: [blog, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :content, id: "comment_content_#{blog.id}" %>
    <%= form.label :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [blog, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="comment">

      <%= form.text_area :content, class:"form-control",placeholder:"Hey !" %>

  </div>

  <div class="actions">
    <%= form.submit "Submit", class:"btn btn-success" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>

  <% comments.each do |comment| %>
    <% if comment.id.present? %>

      <li class="li">
        <div class="comment-content" id ="this_comment_<%= comment.id%>"</div>
        <p class="comment"><%= comment.content %><% if current_user.id == comment.user_id %>
        <%= link_to edit_blog_comment_path(blog, comment), remote: true do %>
        <%= image_tag "edit_comment.png", class: 'insta_icon1', id:'edit1' %>
        <% end %>
        <%= link_to blog_comment_path(comment.blog_id, comment.id), method: :delete, remote: true,
                                          data: { confirm: "Do you really want to delete this?"} do %>
        <%= image_tag "delete.png", class: 'insta_icon1', id:'delete1' %>
        <% end %>
        <% elsif current_user.id == blog.user.id && current_user.id != comment.user_id %>
        <%= link_to blog_comment_path(comment.blog_id, comment.id), method: :delete, remote: true,
                                          data: { confirm: "Do you really want to delete this?"} do %>
        <%= image_tag "delete.png", class: 'insta_icon1' %>
        <% end %>
        <% end %></p>

      </li>
      <hr>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', blog: @blog, comment: @comment %>");
$("#notice").html("<%= j flash[:notice] %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j render 'comments/index', comments: @comment.blog.comments, blog: @comment.blog %>");
$("textarea").val('');
$("#notice").html("<%= j flash[:notice] %>");