config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
root  "blogs#index"
devise_for :users
resources :users, only: [:show]
resources :conversations do
resources :messages
end
resources :favorites
  resources :blogs do
    resources :comments

    collection do
      post :confirm
    end
  end
  #resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    member do
      get :likes
    end

  end
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end
end

app/models/user.rb
class User < ApplicationRecord
  before_save :addrandomusername
 mount_uploader :image, ImageUploader
 has_many :blogs
 has_many :favorites, dependent: :destroy
 #has_many :rails_admin, dependent: :nullify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable #:confirmable
  def online?
   updated_at > 10.minutes.ago
  end
  scope :online, lambda{ where("updated_at > ?", 10.minutes.ago) }

  def addrandomusername
    username = Faker::Internet.username
    self.name=username
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :likes, :update]

 def index
   @users = User.all
 end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update
   @user = User.find(params[:id])
   if @user.update(user_params)
     redirect_to user_path(@user.id)

   else
     render :edit
   end
 end

  def likes
      @favorites = User.find(current_user.id).favorites.order(id: "desc")
    end
private

 def user_params
   params.require(:user).permit(:name, :email, :password,
                                :password_confirmation, :image, :image_cache )
 end

 def correct_user
   user = User.find(params[:id])
   if current_user != user
     redirect_to blogs_path
   end
 end

 def set_user
   @user = User.find(params[:id])
 end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<body class="bckg-im">
  <header class="123">
    <div class="en_tete">
      <%= image_tag "header_border.png", class: 'header_border' %>
      <%= link_to blogs_path do %>
        <%= image_tag "insta.png", class: 'insta_logo' %>
      <% end %>

      <span class='recherche'></span>
      <%= link_to blogs_path do %>
      <%= image_tag "home.jpg", class: 'insta_icon' %>
      <%end%>
      <% if @recipient.present? %>
       <%= link_to conversations_path(sender_id: current_user.id, recipient_id: @recipient), method: :post do %>
      <%= image_tag "insta_messenger.jpg", class: 'insta_icon' %>
      <% end %>
      <% end %>
      <%= link_to likes_user_path(current_user.id) do %>
      <%= image_tag "heart_img.png", class: 'insta_icon' %>
      <% end %>
      <%= link_to user_path(current_user.id) do %>
      <%= image_tag "user.png", class: 'insta_icon' %>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete,data: { confirm: 'Are You Sure ?' } do %>
      <%= image_tag "logout.png", class: 'insta_icon' %>
      <% end %>
      <% if current_user.admin? %>
     <%= link_to rails_admin_path do %>
     <%= image_tag "admin.png", class: 'insta_icon' %>
     <% end %>
     <% end %>
    </div>
  </header>
<main>
<%= form_with(model: @user, local: true, url: user_path(@user.id)) do |f| %>
  <br>
  <p class="comment">Name:<%= @user.name %></p>
  <br>
  <p class="comment">Email Adress: <%= @user.email %></p>
  <%= f.label :'Photo de profil', class:"comment" %>
  <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
  <%= f.submit "Edite", class:"btn btn-outline-warning" %>
<% end %>
</main>
</body>

app/views/users/index.html.erb
<h2>user</h2>
<% @users.each do |user| %>
  <% if user.id != current_user.id %>
    <li>
      <div class="item">
        <%= link_to user.name, user %>
        <%= link_to 'Message', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
      </div>
    </li>
  <% end %>
<% end %>

app/views/users/likes.html.erb
<body class="bckg-im">
  <header class="123">
    <div class="en_tete">
      <%= image_tag "header_border.png", class: 'header_border' %>
      <%= link_to blogs_path do %>
        <%= image_tag "insta.png", class: 'insta_logo' %>
      <% end %>

      <span class='recherche'></span>
      <%= link_to blogs_path do %>
      <%= image_tag "home.jpg", class: 'insta_icon' %>
      <%end%>
      <% if @recipient.present? %>
       <%= link_to conversations_path(sender_id: current_user.id, recipient_id: @recipient), method: :post do %>
      <%= image_tag "insta_messenger.jpg", class: 'insta_icon' %>
      <% end %>
      <% end %>
      <%= link_to likes_user_path(current_user.id) do %>
      <%= image_tag "heart_img.png", class: 'insta_icon' %>
      <% end %>
      <%= link_to user_path(current_user.id) do %>
      <%= image_tag "user.png", class: 'insta_icon' %>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete,data: { confirm: 'Are You Sure ? ?' } do %>
      <%= image_tag "logout.png", class: 'insta_icon' %>
      <% end %>
      <% if current_user.admin? %>
     <%= link_to rails_admin_path do %>
     <%= image_tag "admin.png", class: 'insta_icon' %>
     <% end %>
     <% end %>
    </div>
  </header>
<main>
<h1 class="comment">Favorite Post </h1>
<br>
<% @favorites.each do |favorite| %>
<table>
  <tr>
    <td class="comment">Post Of <%= link_to "#{favorite.blog.user.name}", user_path(favorite.blog.user.id) %></td>
    <td><%= link_to 'details', blog_path(favorite.blog.id) %></td>
  </tr>
  <tr>
    <td>
      <% if favorite.blog.image.file.nil? %>
        <% else %>
        <%= image_tag favorite.blog.image.url %>
      <% end %>
    </td>
  </tr>
  <tr class="comment">
    <td>
      <%= favorite.user.created_at.try(:strftime,"%D") %>
      <%= favorite.blog.content %>
    </td>
  </tr>
  <tr>
    <td>
    <% @favorite = current_user.favorites.find_by(blog_id: favorite.blog.id) %>
    <% if @favorite.present? %>
    <%= link_to 'Delete', favorite_path(id: @favorite.id), method: :delete, class:"btn btn-warning" %>
    <p class="comment">-----------------------------------------------------------------------------------------------------------------------------------------------------</p>
      <% else %>
    <%= link_to 'favoris', favorites_path(blog_id: favorite.blog.id), method: :post%>
    <% end %>
    </td>
  </tr>
  <br>
</table>
<% end %>
<br>
<br>
</main>
</body>

app/views/users/show.html.erb
<body class="bckg-im">
  <header class="123">
    <div class="en_tete">
      <%= image_tag "header_border.png", class: 'header_border' %>
      <%= link_to blogs_path do %>
        <%= image_tag "insta.png", class: 'insta_logo' %>
      <% end %>

      <span class='recherche'></span>
      <%= link_to blogs_path do %>
      <%= image_tag "home.jpg", class: 'insta_icon' %>
      <%end%>
      <% if @recipient.present? %>
       <%= link_to conversations_path(sender_id: current_user.id, recipient_id: @recipient), method: :post do %>
      <%= image_tag "insta_messenger.jpg", class: 'insta_icon' %>
      <% end %>
      <% end %>
      <%= link_to likes_user_path(current_user.id) do %>
      <%= image_tag "heart_img.png", class: 'insta_icon' %>
      <% end %>
      <%= link_to user_path(current_user.id) do %>
      <%= image_tag "user.png", class: 'insta_icon' %>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete,data: { confirm: 'Are You Sure ?' } do %>
      <%= image_tag "logout.png", class: 'insta_icon' %>
      <% end %>
      <% if current_user.admin? %>
     <%= link_to rails_admin_path do %>
     <%= image_tag "admin.png", class: 'insta_icon' %>
     <% end %>
     <% end %>
    </div>
  </header>

<main>
  <h1 class="comment"><%= @user.name %>'s Profile Page</h1>
  <% if current_user.id == @user.id %>
    <p><%= link_to "Edit", edit_user_path(@user.id), class:"btn btn-warning" %></p>
  <% end %>
  <% if @user.image.file.nil? %>
    <%= image_tag 'no_profile_pic_big.png', class: 'profile_img' %>
    <% else %>
    <%= image_tag @user.image.url, class: 'profile_img' %>
  <% end %>

  <br>
  <br>

  <% if current_user.id == @user.id %>
  <%= link_to "Favorite poste", likes_user_path(current_user.id),  class:"btn btn-danger" %>
    <%= link_to 'Message', conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: :post %>

    <br>
    <br>
  <% end %>
  <br>
  <br>
  <br>
</main>